
{% set data = load_setup_py_data() %}

package:
  name: rl_navigation
  version: {{ data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

  entry_points:
    {% for entry in data['entry_points']['console_scripts'] %}
      - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
    {% endfor %}

requirements:
  host:
    - python
    - pip
  run:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest tests

about:
  home: https://github.mit.edu/aiia-suas-disaster-response/rl_navigation
  summary: Training pipeline for RL policies utilizing FlightGoggles for simulation
